class Companies::Setting < ActiveRecord::Base
  belongs_to :company

  SETTING_BOOLEAN_FIELDS = [
    :can_assign_all_users,
    :can_show_lead_phone,
    :global_validation,
    :hide_next_call_date,
    :project_wise_round_robin,
    :call_response_report,
    :biz_integration_enable,
    :inventory_integration_enable,
    :client_integration_enable,
    :broker_integration_enable,
    :enable_whatsapp_action,
    :enable_email_action,
    :enable_lead_tracking,
    :enable_callerdesk_sid,
    :enable_presale_user_visits_report,
    :czentrixcloud_enable,
    :visit_filter_enable,
    :secondary_level_round_robin,
    :back_dated_ncd_allowed,
    :edit_profile_not_allowed,
    :enable_lead_direct_edit,
    :enable_call_center_dashboard,
    :default_lead_user_enable,
    :enable_broker_management,
    :hide_lead_mobile_for_executive,
    :can_send_lead_assignment_mail,
    :way_to_voice_enabled,
    :set_ncd_non_mandatory_for_booked_status,
    :enable_ncd_sort_nulls_last,
    :enable_site_visit_planned_tracker,
    :enable_executive_export_leads,
    :set_svp_default_7_days,
    :enable_booking_done_fields,
    :enable_executive_to_assign_users,
    :enable_country_in_project,
    :enable_advance_visits,
    :disable_visit_finance_section,
    :enable_cards_on_advance_search,
    :enable_inventory_management,
    :enable_meeting_executives,
    :can_clone_lead,
    :open_closed_lead_enabled,
    :can_add_users,
    :enable_lead_log_export,
    :fb_campaign_enabled,
    :project_campaign_enabled,
    :managerwise_closing_executive_active,
    :postsales_integration_active,
    :can_delete_users,
    :restrict_sv_form_duplicate_lead_visit,
    :mobicomm_sms_service_enabled,
    :my_sms_shop_enabled,
    :pg_sms_api_enabled,
    :is_sv_project_enabled,
    :enable_booking_loan_fields,
    :enable_sub_source_report,
    :enable_marketing_report_subsource_filter,
    :enable_source,
    :exotel_sms_integration_enabled,
    :enable_smtp_settings,
    :template_flag_name,
    :sms360_enabled,
    :enable_user_incentive,
    :enable_visit_counter_card,
    :enable_flat_details,
    :closing_executive_round_robin,
    :enable_broker_bulk_update,
    :enable_import_brokers,
    :enable_export_brokers,
    :enable_source_wise_report,
    :enable_expire_block_flat_details,
    :chart_type,
    :enable_customize_status_report,
    :enable_project_share,
    :enable_managerwise_report,
    :disable_marketing_roi_executive_access,
    :enable_sv_form_print,
    :enable_status_wise_notification,
    :enable_client_admin_assigning,
    :enable_restricted_fields,
    :enable_deactivate_leads,
    :enable_partner_crm_integration,
    :enable_sv_partner,
    :enable_lead_number,
    :enable_sv_closing_executive_assignment,
    :enable_accounts,
    :enable_gre_partner_access,
    :enable_gre_source_report,
    :secondary_source_enabled,
    :nine_nine_update_enabled,
    :set_mobile_10_digit_mandatory,
    :nine_nine_profile_id,
    :enable_lead_export,
    :disable_sv_provenance,
    :enable_push_notify_closing_manager,
    :mcube_outbound_number_rotation_enabled,
    :enable_visit_expiring_card,
    :enable_activity_report_user_logs,
    :enable_activity_report_source_logs,
    :enable_project_brochure,
    :enabled_project_wise_access,
    :enable_advance_mcube,
    :enabled_source_wise_search_access,
    :enable_source_wise_sub_source,
    :restrict_duplicate_other_contact_leads,
    :enable_user_wise_assign_all_users,
    :enable_nextel_whatsapp_triggers,
    :enable_mcrm_complete_lead_update,
    :cp_rm_access_enabled,
    :booking_form_enabled,
    :only_10_digit_mobile_number_enabled,
    :enable_campaign_report
  ]

  def default_fields_values
    self.setting_data || {}
  end

  SETTING_BOOLEAN_FIELDS.each do |method|
    define_method("#{method}=") do |val|
      if ["true", "false", "t", "f", "0", "1"].include?(val)
        val = ActiveModel::Type::Boolean.new.cast(val)
      end
      self.setting_data_will_change!
      self.setting_data = (self.setting_data || {}).merge!({"#{method}" => val})
    end
    define_method("#{method}") do
      default_fields_values.dig("#{method}")
    end
  end

end
